
cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD '1234';" -U postgres
